// Yenilikler: güncellemeden sonra yönetim panelinde bir kez gösterilir (Ayarlar → Sürüm'den yeniden açılır).
// En yeni sürüm en üstte; ilk kaydın sürümü paketin sürümüyle aynı olmalı, yoksa pencere çıkmaz. Satırlar kısa olsun,
// ayrıntılar GitHub'daki sürüm notlarında. tr dışındaki diller en'e düşer.
const LHD_CHANGES = [
  { v: '0.16.0',
    tr: ['Telefon (Ayarlar → Telefon), birbirinden bağımsız seçenekler: odalar ya da kategoriler (Işıklar, İklim, Senaryolar, Efektler) ekranın altında; ışıklar karo ya da tek sıra; ışık penceresi alttan açılır. Kategorilerde ışıklar oda oda, sağa sola kaydırarak gezilir.',
      'İklim ve süpürge kartları (Ayarlar → Görünüm): Halo ya da Sade. Sade stilde her cihaz tek satır: iklimde durum, sıcaklık ve hedef, süpürgede durum, pil, başlat ve istasyon. Karta dokununca genişler: hedef − +, aç/kapat, mod, fan, salınım ya da durdur, bul, emiş gücü. Kategorilerdeki İklim sayfasında odalar tek kutuda, ara başlıklarla.',
      'Telefonda kaydırma çubukları cam görünümde: dolgu hafif bir parıltı, açık çubuğun kenarı ışığın renginde.'],
    en: ['Phone (Settings → Phone), independent options: rooms or categories (Lights, Climate, Scenes, Effects) at the bottom of the screen; lights as tiles or one per row; the light window slides up from the bottom. In categories, lights are browsed room by room by swiping left and right.',
      'Climate and vacuum cards (Settings → Look): Halo or Simple. In the simple style each device is one row: for climate the status, temperature and target, for vacuums the status, battery, start and dock. Tap the card to expand it: target − +, power, mode, fan, swing or stop, locate, suction. The Climate category page shows all rooms in one box with subheadings.',
      'Slider bars on phones have a glass look: the fill is a soft glow and a bar that is on gets an edge in the light\'s colour.'] },
  { v: '0.15.0',
    tr: ['Üst şerit (Ayarlar → Görünüm): oda düğmelerinin boyutu ayarlanabilir; Kolona hizala ile düğmeler seçilen kolonun kenarında biter, her ekran boyutunda aynı hizada kalır. Efektler düğmesi hizalı alana alınabilir.',
      'Işık penceresi: Renk, Efekt ya da Segment sekmesine geçince pencere görünmez oluyor ama ekranı kaplamaya devam ediyordu; bir süre hiçbir dokunuş algılanmıyordu. Düzeltildi.',
      'Senaryo düğmeleri: hedefi oda ya da birden çok cihaz olan servisler (ör. bir alanın bütün ışıklarını kapat) artık çalışıyor.',
      'Düğmeli başlıklı bölümler (mevsim düğmeli iklim bölümü) öbür bölümlerle aynı hizadan başlıyor.'],
    en: ['Top bar (Settings → Look): the room buttons can be resized; with Align to a column they end at the edge of the chosen column on every screen size. The Effects button can join the aligned area.',
      'Light window: switching to the Color, Effect or Segment tab made the window invisible while it kept covering the screen, so taps were ignored for a while. Fixed.',
      'Scene buttons: services that target an area or several devices (e.g. turn off all lights in an area) now work.',
      'Sections with a button in the title (the climate section with the season button) now start level with the other sections.'] },
  { v: '0.14.0',
    tr: ['217 yeni renkli simge (★, panoya özel): ışık yerleri (asma tavan şeridi, TV arkası, yatak/koltuk/tezgah altı, niş, süpürgelik...), dikey ve katlanır storlar, ısıtma ve havalandırma, mutfak, banyo, güvenlik, enerji ve sigorta, ağ ve akıllı ev donanımı, bahçe ve havuz, evcil hayvan, bebek, sağlık, oyun, yeni oda simgeleri ve 18 senaryo simgesi (okuma, banyo, romantik, Ramazan, yılbaşı...). Set artık 1522 simge.',
      'Simge aramasında yeni Türkçe kelimeler: havuz, sulama, akvaryum, sigorta, şarj, semaver, şömine, oyun, Ramazan, tansiyon ve daha fazlası.'],
    en: ['217 new colourful icons (★, dashboard-only): light placements (drop-ceiling strip, behind the TV, under the bed/sofa/counter, niche, skirting...), vertical and pleated blinds, heating and ventilation, kitchen, bathroom, security, energy and fuses, network and smart home hardware, garden and pool, pets, baby, health, games, new room icons and 18 scene icons (reading, bath time, romantic, Ramadan, new year...). The set now has 1522 icons.',
      'More Turkish words in the icon search: pool, irrigation, aquarium, fuse, charging, samovar, fireplace, games, Ramadan, blood pressure and more.'] },
  { v: '0.13.0',
    tr: ['Yedek kontrol (Gelişmiş): Home Assistant\'ta iki kez görünen lambaya (ör. Govee LAN ve Matter) ikinci kopyası yedek olarak seçilir. Komut önce hızlı yoldan gider; lamba birkaç saniye içinde cevap vermezse yedekten gönderilir, karonun köşesinde turuncu nokta çıkar.',
      'Duvar anahtarları (Ayarlar → Gelişmiş): yalnız sinyal veren röle bir lambaya bağlanır; elle basınca lamba açılır/kapanır, açarken parlaklık ve kelvin verilebilir. Aynı anahtarı kullanan HA otomasyonu varsa uyarılır.',
      'Yeni servis: lemur_home_dashboard.control (yedekli aç / kapa / tersine çevir).'],
    en: ['Backup control (Advanced): a lamp that shows up twice in Home Assistant (e.g. Govee LAN and Matter) gets its second copy as a backup. The command goes the fast way first; if the lamp does not answer within a few seconds it is sent through the backup and an orange dot appears in the tile\'s corner.',
      'Wall switches (Settings → Advanced): a relay that only gives a signal is bound to a lamp; pressing it toggles the lamp, with optional brightness and kelvin for turning on. You are warned if an HA automation uses the same switch.',
      'New service: lemur_home_dashboard.control (on / off / toggle with backup).'] },
  { v: '0.12.4',
    tr: ['Yatay tutulan telefonda ve dikey tutulan tablette pano telefon düzenine geçer (yazılar artık küçülmüyor, karolar uzamıyor); karo sayısı ekran genişliğine göre artar.',
      'Telefonda medya satırları kutudan taşmıyor; yönetim paneli ve ayarlar dar ekrana sığıyor; ışık penceresinde beyaz ton düğmeleri dar telefonda iki satır.',
      'Daha hızlı: pano dosyası sıkıştırılmış gelir (~580 KB yerine ~170 KB), ışık penceresi yalnız kendi ışıkları değişince yeniden çizilir.'],
    en: ['A phone held sideways and a tablet held upright now get the phone layout (no more tiny text or stretched tiles); the number of tiles grows with the screen width.',
      'Media rows no longer overflow on phones; the admin panel and settings fit narrow screens; the light window\'s white-tone buttons wrap to two rows on small phones.',
      'Faster: the dashboard file is served compressed (~170 KB instead of ~580 KB) and the light window only redraws when its own lights change.'] },
  { v: '0.12.3',
    tr: ['Işık düğmeleri anında tepki verir: dokununca cihazın cevabı beklenmez. Açarken düğme ışığın son renginde yanar; gerçek durum gelince gerekirse düzelir, 5 sn içinde cevap gelmezse eski haline döner.'],
    en: ['Light buttons react instantly: no waiting for the device. Turning on lights the button in the light\'s last colour; it is corrected when the real state arrives and goes back if there is no reply within 5 s.'] },
  { v: '0.12.2',
    tr: ['Ayarlar: "Sürüm ve güncelleme" en üstte; güncellemeler tek dokunuşla denetlenir.'],
    en: ['Settings: "Version and updates" is now at the top; check for updates with one tap.'] },
  { v: '0.12.1',
    tr: ['Güvenlik düzeltmeleri: pencere içeriği, bağlantılar, yedekten geri yükleme ve simge dosyaları denetleniyor.',
      'Besleme: bir dakika içinde ikinci "Besledim" sayılmaz, otomatik yemlik iki kez çalışmaz. Yemlik servisi izinli alanlardan biri olmalı (button, switch, script...).',
      'Yönetici olmayan kullanıcılar (duvar tableti) yemlik servisini ve bildirim hedefini görmez.'],
    en: ['Security fixes: popup content, links, backup restore and icon files are checked.',
      'Feeding: a second "Fed" within a minute is not counted and the automatic feeder does not run twice. The feeder service must be in an allowed domain (button, switch, script...).',
      'Non-admin users (the wall tablet) do not see the feeder service or the notification target.'] },
  { v: '0.12.0',
    tr: ['İkinci satır: durum, son değişim, öznitelik ya da yazı; değer karosunda ad üstte, değer altta seçeneği.',
      'Ad ve ikinci satırda Home Assistant şablonu ({{ }} / {% %}); değer değişince yazı kendiliğinden güncellenir.',
      'Dokununca onay iste: "Evi Kapa çalıştırılsın mı?"',
      'Kart seçici: Halo kartları, Home Assistant kartları ve kurulu özel kartlar listeden; görsel düzenleyici ve canlı önizleme.'],
    en: ['Second line: state, last changed, an attribute or text; a value tile can put the name on top and the value below.',
      'Home Assistant templates ({{ }} / {% %}) in the name and second line; the text updates by itself.',
      'Ask before running: "Run Close the house?"',
      'Card picker: Halo cards, Home Assistant cards and installed custom cards from a list; visual editor and live preview.'] },
  { v: '0.11.0',
    tr: ['Yönetim panelinde Basit ve Gelişmiş mod: Basit modda yalnız temel ayarlar görünür; gelişmiş ayarlar silinmez, çalışmaya devam eder. Üst çubuktan değiştirilir, bu tarayıcıda hatırlanır.',
      'Karmaşık ayarların yanında ? yardım: ne işe yaradığı, nasıl ayarlandığı ve bir örnek.',
      'Basit modda gelişmiş ayarı olan öğe "gelişmiş" işaretiyle görünür.'],
    en: ['Simple and Advanced mode in the admin panel: simple mode shows only the basics; advanced settings are kept and keep working. Switch it in the top bar; it is remembered in this browser.',
      'A ? help next to complex settings: what it does, how to set it up and an example.',
      'In simple mode, items with advanced settings carry an "advanced" mark.'] },
  { v: '0.10.0',
    tr: ['Besleme kartı: kedi, köpek, balık... için besleme hatırlatıcısı. Zamanında yeşil, yaklaşınca sarı, zamanı gelince turuncu, gecikince kırmızı ve yanıp söner.',
      'Karta dokun: "Besledim" (10 sn içinde yeniden dokununca geri alınır). Basılı tut: son beslemeler.',
      'Her N saatte bir ya da günün belli saatlerinde; gecikince telefona bildirim, istersen otomatik yemlik.',
      'Home Assistant\'ta her hayvan için besleme durumu ve "besledim" düğmesi oluşur; otomasyonlarda kullanılabilir.',
      'Bölüm ayarı Aralık; kutuyu doldururken öğeler artık birbirine yapışmaz.',
      'Halo görünümünde ve kart öğelerinde yükseklik, simge ve yazı boyutu; Halo öğenin simgesini kullanır.',
      'Sabit renk ve duruma göre renk (metin değerler de); bölüm içinde alt başlık; satır boyu karoda simge ve yazı yan yana.'],
    en: ['Feeding card: a feeding reminder for a cat, dog, fish... Green on time, yellow when due soon, orange when due, red and blinking when late.',
      'Tap the card: "Fed" (tap again within 10 s to undo). Hold: recent feedings.',
      'Every N hours or at set times of day; a phone notification when late, and an automatic feeder if you have one.',
      'Home Assistant gets a feeding status and a "fed" button for every pet, usable in automations.',
      'Section setting Spacing; items no longer touch when filling the box.',
      'Height, icon and text size for the Halo look and card items; the Halo look uses the item\'s icon.',
      'Fixed colour and colour by state (text values too); subtitles inside a section; a full-row tile puts icon and text side by side.'] },
  { v: '0.9.0',
    tr: ['Öğe ayarı Görünüm: düğme ışıkların yanında karo olabilir; değerler ve cihazlar ince satır ya da düğme, sayısal değerler Halo kartı olarak çizilebilir.',
      'Öğe renkleri: simge rengi, açıkken renk, arka plan tonu; sayısal değerde 4 sınır ve 5 renkle değere göre renk.',
      'Kart öğesine ve Halo görünümüne dokununca / basılı tutunca eylem: kartın kendi tıklaması yerine o çalışır.',
      'Kare karolu kutu da artık kesilmez, karoların boyuna kadar uzar.'],
    en: ['Item setting Look: a button can be a tile next to the lights; values and devices can be thin rows or buttons, numeric values a Halo card.',
      'Item colours: icon colour, colour when on, background tint; numeric values can be coloured by value with 4 limits and 5 colours.',
      'Tap / hold action on card items and the Halo look: it runs instead of the card\'s own tap.',
      'A box with square tiles is no longer cut off either; it grows to fit the tiles.'] },
  { v: '0.8.0',
    tr: ['Bölüme düğme eklenince kutu artık kesilmez: kutu içeriği kadar uzar, ekrana sığmayan sütun kendi içinde kayar.',
      'Bölüm ayarı Doldurma: "Kutuyu doldur" seçilince düğmeler ve karolar kutunun yüksekliğine eşit dağılır.',
      'Bölüm ayarı Hizalama: üst, orta ya da eşit dağıt.',
      'Öğe ayarı Boyut: karo 1×1, 2×1, 1×2, 2×2 ya da satır boyu.',
      'Öğe ayarı Simge boyutu ve Yazı boyutu: küçük, orta, büyük.'],
    en: ['A section no longer cuts off buttons: the box grows with its content and a column that doesn\'t fit the screen scrolls by itself.',
      'Section setting Fill: with "Fill the box", buttons and tiles share the box height evenly.',
      'Section setting Alignment: top, middle or spread evenly.',
      'Item setting Size: a tile can be 1×1, 2×1, 1×2, 2×2 or a full row.',
      'Item settings Icon size and Text size: small, medium, large.'] },
  { v: '0.7.0',
    tr: ['Değer karosu: sensör, zamanlayıcı, sayaç ve seçimler simge, değer + birim ve adıyla görünür; çalışan zamanlayıcı geri sayar.',
      'Öğe ayarları (⚙): ad, simge, açık/kapalı simgesi, dokununca ve basılı tutunca ne olacağı.',
      'Sadece şu durumda göster: öğe, seçilen varlığın durumuna göre görünür ya da hiç çizilmez.',
      'Kart (YAML): bölüme Home Assistant kartı eklenir; düğme bir kartı panonun kendi penceresinde açabilir.',
      'Sette olmayan simgeler artık Home Assistant\'ın düz simgesiyle çizilir.'],
    en: ['Value tile: sensors, timers, counters and selects show their icon, value + unit and name; a running timer counts down.',
      'Item settings (⚙): name, icon, on/off icons, what happens on tap and on hold.',
      'Only show when: an item shows or is not drawn at all depending on an entity\'s state.',
      'Card (YAML): add a Home Assistant card to a section; a button can open a card in the dashboard\'s own window.',
      'Icons not in the set are now drawn with Home Assistant\'s flat icon.'] },
  { v: '0.6.0',
    tr: ['Efekt simgeleri artık panonun kendi kopyasından gelir: Light Effect Card kurulu olmasa da sekmelerde ve öğelerde kullanılabilir.',
      'Ayarlar → Sürüm ve güncelleme: güncellemeyi denetle, HACS ile indir ve Home Assistant\'ı yeniden başlat, hepsi buradan.',
      'Güncellemeden sonra eski panonun açılması sorunu giderildi.',
      'Güncellemeden sonra bu "Yenilikler" penceresi bir kez çıkar; sonra Ayarlar → Sürüm\'den yeniden açılır.',
      'Ayarlar → Yardım → Sorun bildir: sürüm ve cihaz bilgisiyle hazır bir GitHub kaydı açar; kişisel bilgi eklenmez.',
      'Ayarlar → Yedek: bütün pano düzeni tek dosya olarak indirilir ve dosyadan geri yüklenir.'],
    en: ['Effect icons now come from the dashboard\'s own copy: usable on tabs and items even without Light Effect Card.',
      'Settings → Version and updates: check for updates, download with HACS and restart Home Assistant, all from here.',
      'Fixed the old dashboard opening after an update.',
      'After an update this "What\'s new" window shows once; reopen it from Settings → Version.',
      'Settings → Help → Report a problem: opens a GitHub issue with the version and device details; nothing personal is added.',
      'Settings → Backup: download the whole dashboard layout as one file and restore it from a file.'] },
  { v: '0.5.0',
    tr: ['Simge stiline Tek renk eklendi: kapalılar gri, açıklar seçtiğin renkte; istersen ışık lambanın kendi renginde.'],
    en: ['Single colour icon style: devices that are off are grey, those that are on take the colour you pick; optionally a light shows its own colour.'] },
  { v: '0.4.0',
    tr: ['Panodaki bütün simgeler kendi setinden çizilir; simge stili Otomatik, Renkli ya da Düz.',
      'Ayarlarda bir şey değiştirince pencere artık başa atlamıyor; "Yan menüyü gizle" boş şerit bırakmıyor.'],
    en: ['Every icon on the dashboard is drawn from its own set; icon style Automatic, Colourful or Flat.',
      'Changing a setting no longer jumps the window to the top; "Hide sidebar" no longer leaves an empty strip.'] },
  { v: '0.3.0',
    tr: ['Renkli simge seti 1305 simgeye çıktı: oda, ışık, perde, TV, bilgisayar, iklim, güvenlik ve daha fazlası.'],
    en: ['The colourful icon set grew to 1305 icons: rooms, lights, curtains, TVs, computers, climate, security and more.'] },
  { v: '0.2.0',
    tr: ['Renkli simge stili ve simge seçicide renkli simgeler.'],
    en: ['Colourful icon style and colourful icons in the icon picker.'] },
];
