// Yenilikler: güncellemeden sonra yönetim panelinde bir kez gösterilir (Ayarlar → Sürüm'den yeniden açılır).
// En yeni sürüm en üstte; ilk kaydın sürümü paketin sürümüyle aynı olmalı, yoksa pencere çıkmaz. Satırlar kısa olsun,
// ayrıntılar GitHub'daki sürüm notlarında. tr dışındaki diller en'e düşer.
const LHD_CHANGES = [
  { v: '0.12.3',
    tr: ['Işık düğmeleri anında tepki verir: dokununca cihazın cevabı beklenmez. Açarken düğme ışığın son renginde yanar; gerçek durum gelince gerekirse düzelir, 5 sn içinde cevap gelmezse eski haline döner.'],
    en: ['Light buttons react instantly: no waiting for the device. Turning on lights the button in the light\'s last colour; it is corrected when the real state arrives and goes back if there is no reply within 5 s.'] },
  { v: '0.12.2',
    tr: ['Ayarlar: "Sürüm ve güncelleme" en üstte; güncellemeler tek dokunuşla denetlenir.'],
    en: ['Settings: "Version and updates" is now at the top; check for updates with one tap.'] },
  { v: '0.12.1',
    tr: ['Güvenlik düzeltmeleri: pencere içeriği, bağlantılar, yedekten geri yükleme ve simge dosyaları denetleniyor.',
      'Besleme: bir dakika içinde ikinci "Besledim" sayılmaz, otomatik yemlik iki kez çalışmaz. Yemlik servisi izinli alanlardan biri olmalı (button, switch, script...).',
      'Yönetici olmayan kullanıcılar (duvar tableti) yemlik servisini ve bildirim hedefini görmez.'],
    en: ['Security fixes: popup content, links, backup restore and icon files are checked.',
      'Feeding: a second "Fed" within a minute is not counted and the automatic feeder does not run twice. The feeder service must be in an allowed domain (button, switch, script...).',
      'Non-admin users (the wall tablet) do not see the feeder service or the notification target.'] },
  { v: '0.12.0',
    tr: ['İkinci satır: durum, son değişim, öznitelik ya da yazı; değer karosunda ad üstte, değer altta seçeneği.',
      'Ad ve ikinci satırda Home Assistant şablonu ({{ }} / {% %}); değer değişince yazı kendiliğinden güncellenir.',
      'Dokununca onay iste: "Evi Kapa çalıştırılsın mı?"',
      'Kart seçici: Halo kartları, Home Assistant kartları ve kurulu özel kartlar listeden; görsel düzenleyici ve canlı önizleme.'],
    en: ['Second line: state, last changed, an attribute or text; a value tile can put the name on top and the value below.',
      'Home Assistant templates ({{ }} / {% %}) in the name and second line; the text updates by itself.',
      'Ask before running: "Run Close the house?"',
      'Card picker: Halo cards, Home Assistant cards and installed custom cards from a list; visual editor and live preview.'] },
  { v: '0.11.0',
    tr: ['Yönetim panelinde Basit ve Gelişmiş mod: Basit modda yalnız temel ayarlar görünür; gelişmiş ayarlar silinmez, çalışmaya devam eder. Üst çubuktan değiştirilir, bu tarayıcıda hatırlanır.',
      'Karmaşık ayarların yanında ? yardım: ne işe yaradığı, nasıl ayarlandığı ve bir örnek.',
      'Basit modda gelişmiş ayarı olan öğe "gelişmiş" işaretiyle görünür.'],
    en: ['Simple and Advanced mode in the admin panel: simple mode shows only the basics; advanced settings are kept and keep working. Switch it in the top bar; it is remembered in this browser.',
      'A ? help next to complex settings: what it does, how to set it up and an example.',
      'In simple mode, items with advanced settings carry an "advanced" mark.'] },
  { v: '0.10.0',
    tr: ['Besleme kartı: kedi, köpek, balık... için besleme hatırlatıcısı. Zamanında yeşil, yaklaşınca sarı, zamanı gelince turuncu, gecikince kırmızı ve yanıp söner.',
      'Karta dokun: "Besledim" (10 sn içinde yeniden dokununca geri alınır). Basılı tut: son beslemeler.',
      'Her N saatte bir ya da günün belli saatlerinde; gecikince telefona bildirim, istersen otomatik yemlik.',
      'Home Assistant\'ta her hayvan için besleme durumu ve "besledim" düğmesi oluşur; otomasyonlarda kullanılabilir.',
      'Bölüm ayarı Aralık; kutuyu doldururken öğeler artık birbirine yapışmaz.',
      'Halo görünümünde ve kart öğelerinde yükseklik, simge ve yazı boyutu; Halo öğenin simgesini kullanır.',
      'Sabit renk ve duruma göre renk (metin değerler de); bölüm içinde alt başlık; satır boyu karoda simge ve yazı yan yana.'],
    en: ['Feeding card: a feeding reminder for a cat, dog, fish... Green on time, yellow when due soon, orange when due, red and blinking when late.',
      'Tap the card: "Fed" (tap again within 10 s to undo). Hold: recent feedings.',
      'Every N hours or at set times of day; a phone notification when late, and an automatic feeder if you have one.',
      'Home Assistant gets a feeding status and a "fed" button for every pet, usable in automations.',
      'Section setting Spacing; items no longer touch when filling the box.',
      'Height, icon and text size for the Halo look and card items; the Halo look uses the item\'s icon.',
      'Fixed colour and colour by state (text values too); subtitles inside a section; a full-row tile puts icon and text side by side.'] },
  { v: '0.9.0',
    tr: ['Öğe ayarı Görünüm: düğme ışıkların yanında karo olabilir; değerler ve cihazlar ince satır ya da düğme, sayısal değerler Halo kartı olarak çizilebilir.',
      'Öğe renkleri: simge rengi, açıkken renk, arka plan tonu; sayısal değerde 4 sınır ve 5 renkle değere göre renk.',
      'Kart öğesine ve Halo görünümüne dokununca / basılı tutunca eylem: kartın kendi tıklaması yerine o çalışır.',
      'Kare karolu kutu da artık kesilmez, karoların boyuna kadar uzar.'],
    en: ['Item setting Look: a button can be a tile next to the lights; values and devices can be thin rows or buttons, numeric values a Halo card.',
      'Item colours: icon colour, colour when on, background tint; numeric values can be coloured by value with 4 limits and 5 colours.',
      'Tap / hold action on card items and the Halo look: it runs instead of the card\'s own tap.',
      'A box with square tiles is no longer cut off either; it grows to fit the tiles.'] },
  { v: '0.8.0',
    tr: ['Bölüme düğme eklenince kutu artık kesilmez: kutu içeriği kadar uzar, ekrana sığmayan sütun kendi içinde kayar.',
      'Bölüm ayarı Doldurma: "Kutuyu doldur" seçilince düğmeler ve karolar kutunun yüksekliğine eşit dağılır.',
      'Bölüm ayarı Hizalama: üst, orta ya da eşit dağıt.',
      'Öğe ayarı Boyut: karo 1×1, 2×1, 1×2, 2×2 ya da satır boyu.',
      'Öğe ayarı Simge boyutu ve Yazı boyutu: küçük, orta, büyük.'],
    en: ['A section no longer cuts off buttons: the box grows with its content and a column that doesn\'t fit the screen scrolls by itself.',
      'Section setting Fill: with "Fill the box", buttons and tiles share the box height evenly.',
      'Section setting Alignment: top, middle or spread evenly.',
      'Item setting Size: a tile can be 1×1, 2×1, 1×2, 2×2 or a full row.',
      'Item settings Icon size and Text size: small, medium, large.'] },
  { v: '0.7.0',
    tr: ['Değer karosu: sensör, zamanlayıcı, sayaç ve seçimler simge, değer + birim ve adıyla görünür; çalışan zamanlayıcı geri sayar.',
      'Öğe ayarları (⚙): ad, simge, açık/kapalı simgesi, dokununca ve basılı tutunca ne olacağı.',
      'Sadece şu durumda göster: öğe, seçilen varlığın durumuna göre görünür ya da hiç çizilmez.',
      'Kart (YAML): bölüme Home Assistant kartı eklenir; düğme bir kartı panonun kendi penceresinde açabilir.',
      'Sette olmayan simgeler artık Home Assistant\'ın düz simgesiyle çizilir.'],
    en: ['Value tile: sensors, timers, counters and selects show their icon, value + unit and name; a running timer counts down.',
      'Item settings (⚙): name, icon, on/off icons, what happens on tap and on hold.',
      'Only show when: an item shows or is not drawn at all depending on an entity\'s state.',
      'Card (YAML): add a Home Assistant card to a section; a button can open a card in the dashboard\'s own window.',
      'Icons not in the set are now drawn with Home Assistant\'s flat icon.'] },
  { v: '0.6.0',
    tr: ['Efekt simgeleri artık panonun kendi kopyasından gelir: Light Effect Card kurulu olmasa da sekmelerde ve öğelerde kullanılabilir.',
      'Ayarlar → Sürüm ve güncelleme: güncellemeyi denetle, HACS ile indir ve Home Assistant\'ı yeniden başlat, hepsi buradan.',
      'Güncellemeden sonra eski panonun açılması sorunu giderildi.',
      'Güncellemeden sonra bu "Yenilikler" penceresi bir kez çıkar; sonra Ayarlar → Sürüm\'den yeniden açılır.',
      'Ayarlar → Yardım → Sorun bildir: sürüm ve cihaz bilgisiyle hazır bir GitHub kaydı açar; kişisel bilgi eklenmez.',
      'Ayarlar → Yedek: bütün pano düzeni tek dosya olarak indirilir ve dosyadan geri yüklenir.'],
    en: ['Effect icons now come from the dashboard\'s own copy: usable on tabs and items even without Light Effect Card.',
      'Settings → Version and updates: check for updates, download with HACS and restart Home Assistant, all from here.',
      'Fixed the old dashboard opening after an update.',
      'After an update this "What\'s new" window shows once; reopen it from Settings → Version.',
      'Settings → Help → Report a problem: opens a GitHub issue with the version and device details; nothing personal is added.',
      'Settings → Backup: download the whole dashboard layout as one file and restore it from a file.'] },
  { v: '0.5.0',
    tr: ['Simge stiline Tek renk eklendi: kapalılar gri, açıklar seçtiğin renkte; istersen ışık lambanın kendi renginde.'],
    en: ['Single colour icon style: devices that are off are grey, those that are on take the colour you pick; optionally a light shows its own colour.'] },
  { v: '0.4.0',
    tr: ['Panodaki bütün simgeler kendi setinden çizilir; simge stili Otomatik, Renkli ya da Düz.',
      'Ayarlarda bir şey değiştirince pencere artık başa atlamıyor; "Yan menüyü gizle" boş şerit bırakmıyor.'],
    en: ['Every icon on the dashboard is drawn from its own set; icon style Automatic, Colourful or Flat.',
      'Changing a setting no longer jumps the window to the top; "Hide sidebar" no longer leaves an empty strip.'] },
  { v: '0.3.0',
    tr: ['Renkli simge seti 1305 simgeye çıktı: oda, ışık, perde, TV, bilgisayar, iklim, güvenlik ve daha fazlası.'],
    en: ['The colourful icon set grew to 1305 icons: rooms, lights, curtains, TVs, computers, climate, security and more.'] },
  { v: '0.2.0',
    tr: ['Renkli simge stili ve simge seçicide renkli simgeler.'],
    en: ['Colourful icon style and colourful icons in the icon picker.'] },
];
